/**
 * Generic, cross-domain error codes for space/list/sublist/task/status auth guards -- kept
 * separate from lib/auth/error-codes.js, whose codes are specific to the sign-up/in/out flow.
 */
export const NOT_AUTHENTICATED = 'NOT_AUTHENTICATED';
export const TASK_INVALID_PRIORITY = 'TASK_INVALID_PRIORITY';
export const HOME_LOAD_FAILED = 'HOME_LOAD_FAILED';
export const SPACE_NOT_FOUND = 'SPACE_NOT_FOUND';
export const ALREADY_MEMBER = 'ALREADY_MEMBER';
export const REQUEST_NOT_FOUND = 'REQUEST_NOT_FOUND';
export const PERMISSION_READ_ONLY = 'PERMISSION_READ_ONLY';
export const PERMISSION_RESTRICTED_NOT_OWN = 'PERMISSION_RESTRICTED_NOT_OWN';
export const PERMISSION_NOT_A_MEMBER = 'PERMISSION_NOT_A_MEMBER';
export const INVITE_INVALID = 'INVITE_INVALID';
export const INVITE_EXPIRED = 'INVITE_EXPIRED';
export const INVITE_EMAIL_MISMATCH = 'INVITE_EMAIL_MISMATCH';
export const INVITE_RATE_LIMITED = 'INVITE_RATE_LIMITED';
export const TAG_ID_REQUIRED = 'TAG_ID_REQUIRED';
export const TAG_NOT_FOUND = 'TAG_NOT_FOUND';
export const TAG_SPACE_ID_REQUIRED = 'TAG_SPACE_ID_REQUIRED';
export const TAG_DELETE_FAILED = 'TAG_DELETE_FAILED';
export const TAG_ALREADY_ON_TASK = 'TAG_ALREADY_ON_TASK';
export const TASK_DUE_DATE_REQUIRED = 'TASK_DUE_DATE_REQUIRED';
export const SPACE_SETTINGS_OWNER_ONLY = 'SPACE_SETTINGS_OWNER_ONLY';
export const TASK_SUBTASK_CAP_REACHED = 'TASK_SUBTASK_CAP_REACHED';
export const SPACE_SUBTASK_CAP_INVALID = 'SPACE_SUBTASK_CAP_INVALID';
